/*
 * NOTE: This class is auto generated by the swagger code generator program (1.0.16).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.model.Constants;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@SuppressWarnings("ALL")
@Api(value = "constants", description = "the constants API")
public interface ConstantsApi {

    @ApiOperation(value = "getConstants", nickname = "constants", notes = "get pre-defined constants", response = Constants.class, tags={ "developers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Contants Detail", response = Constants.class) })
    @RequestMapping(value = "/constants",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Constants> constants();

}
