/*
 * LicenseBroker
 * Limits usage of a license
 *
 * OpenAPI spec version: 1.0.0
 * Contact: SwingGuy1024@yahoo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
